version: 2

updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      dev-dependencies:
        dependency-type: development
    versioning-strategy: increase

  - package-ecosystem: pip
    directories:
      - /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      dev-dependencies:
        dependency-type: development
    versioning-strategy: increase
