sync_changes_to_github:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "kudoai/chatgpt-js"
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git clone https://gitlab.com/kudoai/chatgpt-js.git
    - git push --force -o ci.skip "https://${GITHUB_SYNC_PAT}@github.com/KudoAI/chatgpt.js.git" HEAD:main
