name: Sync starters/greasemonkey/ to KudoAI/chatgpt.js-greasemonkey-starter/

on:
  push:
    branches: [main]
    paths: [starters/greasemonkey/**]

permissions:
  contents: read

jobs:
  build:
    if: (github.repository == 'KudoAI/chatgpt.js') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout KudoAI/chatgpt.js
        uses: actions/checkout@v5
        with:
          path: KudoAI/chatgpt.js

      - name: Checkout KudoAI/chatgpt.js-greasemonkey-starter
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: KudoAI/chatgpt.js-greasemonkey-starter
          path: KudoAI/chatgpt.js-greasemonkey-starter

      - name: Sync/starters/greasemonkey/ to KudoAI/chatgpt.js-greasemonkey-starter/
        run: |
          rsync -avhr --delete --filter={'P /.*','P /eslint*','P /package*.json'} \
            "${{ github.workspace }}/KudoAI/chatgpt.js/starters/greasemonkey/" \
            "${{ github.workspace }}/KudoAI/chatgpt.js-greasemonkey-starter/"

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Config committer
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global commit.gpgsign true
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"

      - name: Push changes to KudoAI/chatgpt.js-greasemonkey-starter
        run: |
          cd ${{ github.workspace }}/KudoAI/chatgpt.js-greasemonkey-starter
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from https://github.com/KudoAI/chatgpt.js]" || true
          git push
