name: Validate links on push + PR

on:
  push:
    paths: ['**/*.md']
  pull_request:
    paths: ['**/*.md']
  workflow_dispatch:

jobs:
  linkinator:
    if: ${{ github.event.head_commit.author.name != 'kudo-sync-bot' }} # skip auto bump commits containing future links
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: JustinBeckwith/linkinator-action@7b6b0bc671f6264e1a8daa4488a5bd91ce61dcd4 # v2.4.2
        with:
          paths: '**/*.md'
          statusCodes: '{ "429": "skip", "502": "skip", "999": "skip" }'
          linksToSkip: 'npmjs\.com|(?:LICENSE\.md|transparent)$'
